### ISSUE TITLE
Написать сервис авторизации

### ISSUE THREAD

**Issue by pepelulka** [Pepelulka-Inc/animeshki#9]
1. Надо будет нормально продумать как другие сервисы будут узнавать о том, что пользователь зареган
2. Использовать JWT токены (потому что это круто)
3. Пользователь регается по логину и паролю
4. Добавить кеширование в редиске
5. Добавить описание ручек и примерного механизма авторизации в яндекс вику
6. Добавить админские ручки

**Comment by kumaroid** [comment]
какие жевете токены _**бля**_

**Comment by pepelulka** [comment]
> какие жевете токены _**бля**_

Ладно можно без них пофик

**Comment by kumaroid** [comment]
ой спасииибкииии хахаааа
